### PR TITLE
Do not allow templates that are in use to be deleted.

### LINKED ISSUE #123: Messages with missing templates cannot be deleted from the Admin Messages Queue
This was observed on a clean install of Drupal 8.1 and 8.2 with the message stack enabled. If you have messages that were previously created from message templates and you then delete the templates that those message werre based on, you will get an error when attempting to delete those messages from the Admin Messages Queue. 

To reproduce:
1. Enable the message stack modules including the example modules
2. Enable the forum and comment module 
3. Create a forum topic and add a few comments to generate a few messages
4. Go to /admin/structure/message and delete either the template for new nodes or new comments
5. Go to /admin/content/messages and you'll notice that the message rows that correspond to the deleted template are now blank
6. Try to delete one of those rows

The result will be an error like this:

> Error: Call to a member function label() on null in Drupal\message\Form\DeleteMultiple->Drupal\message\Form{closure}() (line 110 of /{your_path}/modules/message/src/Form/DeleteMultiple.php).

When a message template is deleted from the site, all corresponding messages should also be cleared out at the same time.

### PR DESCRIPTION
**Pull request by jhedstrom**
- Fixes #123 

This mimics the approach the node module uses to disallow templates that are in use from being deleted via the UI.

### CODE REVIEW

File: src/Form/MessageTemplateDeleteConfirm.php [hunk 1]
```diff
@@ -8,15 +8,43 @@
...
 
   /**
+   * The query factory to create entity queries.
+   *
+   * @var \Drupal\Core\Entity\Query\QueryFactory
+   */
+  protected $queryFactory;
+
+  /**
+   * Constructs a new NodeTypeDeleteConfirm object.
```
Comment (amitaibu) [inline src/Form/MessageTemplateDeleteConfirm.php]: NodeTypeDeleteConfirm  => MessageTemplateDeleteConfirm

**Review by amitaibu — COMMENTED** [review]
Minor correction, but rest looks good. After that can be merged.

File: src/Form/MessageTemplateDeleteConfirm.php (hunk 1 above)
Comment (jhedstrom) [reply src/Form/MessageTemplateDeleteConfirm.php]: Good catch :)

**Comment by jhedstrom** [comment]
I'm going to cut a new alpha, so merged this in.
