### PR TITLE
Store input format for message templates

### LINKED ISSUE #128: Input format isn't stored with message templates
To reproduce:
1. Add a new template with 3 text areas, select a different input format for each.
2. Save the template.
3. Edit the template, and note that the input format has reverted to the default one for the site.

### PR DESCRIPTION
**Pull request by jhedstrom**
- Fixes #128 

Related #139

### CODE REVIEW

**Comment by jhedstrom** [comment]
@amitaibu ready for review!

File: src/Entity/MessageTemplate.php [hunk 1]
```diff
@@ -253,9 +262,23 @@ public function getText($langcode = Language::LANGCODE_NOT_SPECIFIED, $delta = N
       $text = $translated_text ?: [];
     }
 
+    // Process text format.
+    foreach ($text as $key => $item) {
+      // Call the renderer directly instead of adding a dependency on the Filter
```
Comment (amitaibu) [inline src/Entity/MessageTemplate.php:267]: is this to avoid the a hard dependency on filter module?

File: src/Entity/MessageTemplate.php [hunk 2]
```diff
@@ -282,7 +305,9 @@ public static function create(array $values = []) {
    * {@inheritdoc}
    */
   public function preSave(EntityStorageInterface $storage) {
-    $this->text = array_filter($this->text);
+    $this->text = array_filter($this->text, function ($a) {
```
Comment (amitaibu) [inline src/Entity/MessageTemplate.php]: I'm not totaly clear what we do here. also I think `$a` should get a more descriptive name. maybe `$delta`, or `$partial`?

File: src/Form/MessageTemplateForm.php [hunk 3]
```diff
@@ -170,16 +171,18 @@ public static function addMoreAjax(array $form, FormStateInterface $form_state)
...
-    $this->entity->set('text', $values);
-    $this->entity->save();
+    // Sort by weight.
+    $text = $form_state->getValue('text');
+    usort($text, function ($a, $b) {
+      return SortArray::sortByKeyInt($a, $b, '_weight');
+    });
+    // Do not store weight, as these are now sorted.
+    $text = array_map(function ($a) {
+      unset($a['_weight']); return $a;
```
Comment (amitaibu) [inline src/Form/MessageTemplateForm.php]: should be in separate lines

Comment (amitaibu) [reply src/Form/MessageTemplateForm.php]: is this a common practice? What's the down side of keeping the weight

(just asking, sorting before saving looks fine)

File: src/FormElement/MessageTemplateMultipleTextField.php [hunk 4]
```diff
@@ -86,54 +86,44 @@ public function textField(&$form, FormStateInterface $form_state, $text = []) {
...
     }
   }
 
   /**
    * Return a single text area element.
+   *
+   * @param int $delta
+   *   Delta for the element.
+   * @param array $text
+   *   Array containing 'value' and optionally 'format' for a text_format
```
Comment (amitaibu) [inline src/FormElement/MessageTemplateMultipleTextField.php:107]: When is the case we won't a `format`?

File: src/FormElement/MessageTemplateMultipleTextField.php [hunk 5]
```diff
@@ -86,54 +86,44 @@ public function textField(&$form, FormStateInterface $form_state, $text = []) {
...
+   *   element.
+   *
+   * @return array
+   *   The single form element.
```
Comment (amitaibu) [inline src/FormElement/MessageTemplateMultipleTextField.php]: nitpick: `A Single ..`

File: tests/src/Kernel/MessageTemplateCreateTrait.php [hunk 6]
```diff
@@ -35,6 +35,20 @@ protected function createMessageTemplate($template, $label, $description, array
         'clear' => FALSE,
       ],
     ];
+
+    // If the $text array is simple text values, transform to text + format.
```
Comment (amitaibu) [inline tests/src/Kernel/MessageTemplateCreateTrait.php:39]: not clear why `$detail['format']` can be empty

File: src/Entity/MessageTemplate.php (hunk 2 above)
Comment (amitaibu) [reply src/Entity/MessageTemplate.php]: btw, would that be a good time to rename the word `partial` to `delta`? 😄

File: tests/src/Unit/Entity/MessageTemplateTest.php [hunk 7]
```diff
@@ -108,4 +122,96 @@ public function testIsLocked() {
...
+    $expected = [
+      '<div>foo text</div>',
+      'bar text',
+    ];
+    $this->assertEquals($expected, $this->messageTemplate->getText());
+
+    // Language without translation should return empty array.
+    // @todo Is this correct? Why not return untranslated text?
+    $default_language = $this->prophesize(Language::class);
+    $mock_template = $this->prophesize(MessageTemplate::class);
```
Comment (amitaibu) [inline tests/src/Unit/Entity/MessageTemplateTest.php]: `$mock_template` => `$message_template`

File: tests/src/Unit/Entity/MessageTemplateTest.php [hunk 8]
```diff
@@ -108,4 +122,96 @@ public function testIsLocked() {
...
+    \Drupal::getContainer()->set('renderer', $renderer->reveal());
+
+    $expected = [
+      '<div>foo text</div>',
+      'bar text',
+    ];
+    $this->assertEquals($expected, $this->messageTemplate->getText());
+
+    // Language without translation should return empty array.
+    // @todo Is this correct? Why not return untranslated text?
```
Comment (amitaibu) [inline tests/src/Unit/Entity/MessageTemplateTest.php]: The behavior is probably an edge case, but I think it  right. If for example you have activity stream in English and Hebrew, and the dev didn't translate a template from Hebrew (default language) to English - you, as a non-Heberw speaker, will prefer not to see anything rather than the hebrew.

On the other hand, I can teach you some Hebrew 😜

File: tests/src/Unit/Entity/MessageTemplateTest.php [hunk 9]
```diff
@@ -108,4 +122,96 @@ public function testIsLocked() {
     $this->assertFalse($this->messageTemplate->isLocked());
   }
 
+  /**
+   * Tests the getText method.
+   *
+   * @covers ::getText
+   */
+  public function testGetText() {
```
Comment (amitaibu) [inline tests/src/Unit/Entity/MessageTemplateTest.php]: wow, it's really nice to see this as unit test!

I think it's worth spliting it to smaller methods, as right now i kind of checks everything 😄

**Review by amitaibu — COMMENTED** [review]
Thank you so much for providing such awesome PRs!

I've added a few questions and comments.

I have tried to create a message-template in Hebrew. It worked, however I didn't find how to export the Hebrew version. What am I'm missing?

**Comment by jhedstrom** [comment]
> I have tried to create a message-template in Hebrew. It worked, however I didn't find how to export the Hebrew version. What am I'm missing?

I didn't know either, but asked Alex Pott and he showed me that if you run, for instance `drush config-export`, the translations appear in a subdirectory called `language`. If you look at a translated message, you'll see that only the _translatable_ parts are exported:

```
gP6UkhH6Auo_sNDWtBHqxnTRmoFo2K85SXIivKS3QinnkEg8hg/sync/language/he/message.template.bb.yml
description: translated text here
text:
  -
    value: "<p>TRANSLATION 1</p>\r\n"
    format: basic_html
  -
    value: "<p>TRANSLATION 2</p>\r\n"
    format: restricted_html
```

File: src/Entity/MessageTemplate.php (hunk 1 above)
Comment (jhedstrom) [reply src/Entity/MessageTemplate.php:267]: Yeah, although I've added the `text` module as a dependency, which in turn depends on `filter`, but I'm inclined to leave this as-is for easier unit testing (otherwise, for any unit test, we'd need to redeclare that function in the test).

File: src/Entity/MessageTemplate.php (hunk 2 above)
Comment (jhedstrom) [reply src/Entity/MessageTemplate.php]: I've fixed this (not yet pushed). I think `partial` makes more sense than `delta`, which is fairly generic.

File: src/Form/MessageTemplateForm.php (hunk 3 above)
Comment (jhedstrom) [reply src/Form/MessageTemplateForm.php]: Initially during testing, I was having problems storing weight (without running into schema exceptions). Since the `text_format` property is a compound one (consisting of `value` and `format`), I wasn't immediately clear on how to store a third property side-by-side with those in terms of schema declaration. I could add a `@todo` here to eventually store weight? However, since they are sorted prior to storage, I'm not sure storing weight buys us anything.

Comment (jhedstrom) [reply src/Form/MessageTemplateForm.php]: Oh, and also, using `_weight` added some magic to the form dragging--when I renamed it to just `weight`, the dragging broke, and I didn't dive into why that was the case.

File: src/FormElement/MessageTemplateMultipleTextField.php (hunk 4 above)
Comment (jhedstrom) [reply src/FormElement/MessageTemplateMultipleTextField.php:107]: When adding a new template, there won't be an existing `format` set.

``` php
    // Increase number of elements if requested, or none exist.
    $trigger_element = $form_state->getTriggeringElement();
    if (!empty($trigger_element['#add_more']) || !$start_key) {
      $form['text'][] = $this->singleElement($start_key + 1, ['value' => '']);
    }
```

The call to `filter_default_format()` could be in this code instead of in the `singleElement` method...

File: tests/src/Kernel/MessageTemplateCreateTrait.php (hunk 6 above)
Comment (jhedstrom) [reply tests/src/Kernel/MessageTemplateCreateTrait.php:39]: In this case, we could require all callers to specify a `format`, but since this is a trait for making testing easier, I initially decided to support the legacy input of just an array of text strings:

``` php
$text = [
  'text string one',
  'text string two',
];
```

as opposed to updating all callers to use the now more verbose input:

``` php
$text = [
  [
    'value' => 'text string one',
   'format' => 'some_format',
  ],
  ...
];
```

**Comment by jhedstrom** [comment]
@amitaibu should be ready for another review!

**Comment by amitaibu** [comment]
I haven't forgotten about this, just missing the time. I'll pickup in a couple of days.

**Comment by jhedstrom** [comment]
Bump =)

**Comment by amitaibu** [comment]
Sorry! Just hectic days. So in order for me not to block - go ahead and
merge all you awesome PRs.  I can revisit if needed post-mortem.

**Comment by jhedstrom** [comment]
Sounds good. File follow-ups as needed :)
